RunAction "Mobile_Login", oneIteration
RunAction "Mobile_CreateOrder", oneIteration
RunAction "Mobile_Logout", oneIteration
RunAction "Web_Login", oneIteration
RunAction "Web_ViewOrder", oneIteration
RunAction "ChatBot", oneIteration
RunAction "Shipping_Login", oneIteration
RunAction "Web_Logout", oneIteration
RunAction "SAP_CreateOrder", oneIteration
